from __future__ import annotations

from enum import Enum


class DecisionState(str, Enum):
    REJECTED = "REJECTED"
    RESEARCH_CANDIDATE = "RESEARCH_CANDIDATE"
    WATCHLIST = "WATCHLIST"
    APPROVED_THESIS = "APPROVED_THESIS"
    APPROVED_VALUATION_ZONE = "APPROVED_VALUATION_ZONE"
    TECHNICAL_WAIT = "TECHNICAL_WAIT"
    STARTER_ALLOWED = "STARTER_ALLOWED"
    ADD_ALLOWED = "ADD_ALLOWED"
    HOLD = "HOLD"
    TRIM_CANDIDATE = "TRIM_CANDIDATE"
    EXIT_THESIS_BROKEN = "EXIT_THESIS_BROKEN"
    BLOCKED_BY_RISK = "BLOCKED_BY_RISK"
    NO_ACTION = "NO_ACTION"


class AILayer(str, Enum):
    COMPUTE_ACCELERATORS = "COMPUTE_ACCELERATORS"
    CUSTOM_SILICON = "CUSTOM_SILICON"
    MEMORY_HBM_DRAM = "MEMORY_HBM_DRAM"
    STORAGE_NAND_SSD_HDD = "STORAGE_NAND_SSD_HDD"
    FOUNDRY = "FOUNDRY"
    SEMICONDUCTOR_EQUIPMENT = "SEMICONDUCTOR_EQUIPMENT"
    NETWORKING_OPTICAL = "NETWORKING_OPTICAL"
    HYPERSCALE_CLOUD = "HYPERSCALE_CLOUD"
    DATA_CENTER_POWER_COOLING = "DATA_CENTER_POWER_COOLING"
    DATA_CENTER_REIT = "DATA_CENTER_REIT"
    AI_SOFTWARE = "AI_SOFTWARE"
    CYBERSECURITY = "CYBERSECURITY"
    DATA_PLATFORM = "DATA_PLATFORM"
    OTHER_AI_BENEFICIARY = "OTHER_AI_BENEFICIARY"
    NOT_RELEVANT = "NOT_RELEVANT"


class Confidence(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class ThesisStatus(str, Enum):
    NOT_STARTED = "NOT_STARTED"
    DRAFT = "DRAFT"
    APPROVED = "APPROVED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    BROKEN = "BROKEN"


class EarningsThesisChange(str, Enum):
    STRENGTHENED = "STRENGTHENED"
    UNCHANGED = "UNCHANGED"
    WEAKENED = "WEAKENED"
    BROKEN = "BROKEN"


class TechnicalRegime(str, Enum):
    SUPPORTIVE = "SUPPORTIVE"
    STABILISING = "STABILISING"
    WEAKENING = "WEAKENING"
    BROKEN = "BROKEN"


class DrawdownMode(str, Enum):
    NORMAL = "NORMAL"
    CAUTION_REVIEW = "CAUTION_REVIEW"
    REDUCE_AGGRESSIVE_NEW_BUYS = "REDUCE_AGGRESSIVE_NEW_BUYS"
    FREEZE_WEAK_THESIS_ADDITIONS = "FREEZE_WEAK_THESIS_ADDITIONS"
    RISK_CONTROL = "RISK_CONTROL"
    DEFENSIVE = "DEFENSIVE"
    HARD_AUDIT = "HARD_AUDIT"


class RiskStyle(str, Enum):
    CONSERVATIVE = "CONSERVATIVE"
    BALANCED = "BALANCED"
    AGGRESSIVE = "AGGRESSIVE"


class BaseCurrency(str, Enum):
    USD = "USD"
    SGD = "SGD"
    MYR = "MYR"


class Country(str, Enum):
    SINGAPORE = "Singapore"
    MALAYSIA = "Malaysia"
    OTHER = "Other"
